syntax_review_task:
  description: "Use the markdown_validation_tool to review the file(s) at this path:\
    \ {filename}.\nBe sure to pass only the file path to the markdown_validation_tool.\n\
    Use the following format to call the markdown_validation_tool:\nDo I need to use\
    \ a tool? Yes\nAction: markdown_validation_tool\nAction Input: {filename}\n\n\
    Get the validation results from the tool and then summarize it into a list of\
    \ changes\nthe developer should make to the document.\nDO NOT recommend ways to\
    \ update the document.\nDO NOT change any of the content of the document or add\
    \ content to it. \nIt is critical to your task to only respond with a list of\
    \ changes.\n\nIf you already know the answer or if you do not need to use a tool,\
    \ \nreturn it as your Final Answer.\n"
  expected_output: |
    A list of changes the developer should make to the document based on the markdown validation results.
